### ISSUE TITLE
Error while loading plugins

### ISSUE THREAD

**Issue by rehank30** [intelsdi-x/snap-plugin-collector-facter#22]
when i try to load the plugin using the command : snaptel plugin load snap-plugin-collector-facter 
it is showing the following error on my Mac machine:
Error loading plugin:
fork/exec /tmp/400102727/snap-plugin-collector-facter: exec format error

**Comment by mkleina** [comment]
This is architecture incompatibility error. It seems that you are trying to load plugin binary compiled for Linux on Mac machine. Currently there is no release for Mac, but we will add it in near future.

For now, as quick workaround you can try to modify ./scripts/build.sh and change 
```
export GOOS=linux
export GOARCH=amd64
```
to
```
export GOOS=darwin
export GOARCH=amd64
```
then "exec format error" should be gone. Plugin was not officialy tested on Mac yet, but I think it should work.

**Comment by IzabellaRaulin** [comment]
@rehank30 - the build for dawin has been added to the latest release - you can find it here [snap-plugin-collector-facter/releases](https://github.com/intelsdi-x/snap-plugin-collector-facter/releases/tag/9). Could you check if this binary works on your machine. If it still does not work, please re-open this issue and let us know what happens. Thank You.
